2.017.17: robustification and cleanup of Robert's previous CLISP checkin.

diff --git a/test/stderr b/test/stderr
--- a/test/stderr
+++ b/test/stderr
@@ -3,5 +3,4 @@
 # This script simply writes some text to STDERR, to check and
 # make sure that ASDF:RUN-SHELL-COMMAND handles it properly.
 
-echo "Writing to standard error." > /dev/stderr
-
+echo "Writing to standard error." >& 2
